sudo: false
language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
install: pip install -r dev-requirements.txt
script:
  - flake8 sendgrid_backend/
  - isort -rc ./
  - black --check ./
  - mypy sendgrid_backend/
  - tox
